# Docker image
# Build a Docker image to deploy, run, or push to a container registry.
# Add steps that use Docker Compose, tag images, push to a registry, run an image, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

pool:
  vmImage: 'Ubuntu 16.04'

variables:
  imageName: '$(dockerId).azurecr.io/genericstunnel:$(build.buildId)'
  imageNameLatest: '$(dockerId).azurecr.io/genericstunnel:latest'

steps:
- script: docker build -f Docker/Dockerfile -t $(imageName) -t $(imageNameLatest) .
  displayName: 'docker build'
- script: |
    docker login -u $(dockerId) -p $(dockerpswd) $(dockerId).azurecr.io
    docker push $(dockerId).azurecr.io/$(imageName)
    docker push $(dockerId).azurecr.io/$(imageNameLatest)